name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
publish_to: none
version: 2.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git: https://github.com/kumsumit/flutter_secure_storage_platform_interface.git
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.5.0 <2.0.0"

dev_dependencies:
  very_good_analysis: ^7.0.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
